config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :bookmarks, only: [:destroy, :create]
  end
  
  get 'about' => 'welcome#about'

 
  
  root to: 'welcome#index'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  

  
  def create
    @topic = Topic.find(params[:topic_id])
    @bookmarks = @topic.bookmarks
    @bookmark = @topic.bookmarks.build(params.require(:bookmark).permit(:link, :topic_id))
    @bookmark.topic = @topic
    @new_bookmark = Bookmark.new
    if @bookmark.save
      flash[:notice] = "Bookmark was saved"
      redirect_to @topic
    else
      flash[:error] = "There was an error, please try again later"
      redirect_to @topic
    end
  end
  
  def destroy
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.topic = @topic
    
    if @bookmark.destroy
      flash[:notice] = "Bookmark was destroyed successfully"
      redirect_to [@topic]
    else
      flash[:error] = "There was an error, please try again later"
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
 
  def index
    @topics = Topic.all
  end
  
  def new
    @topic = Topic.new
  end
  
  def show
    @topic = Topic.find(params[:id])  
    @bookmarks = @topic.bookmarks
  end
  
  def create
    @topic = Topic.new(params.require(:topic).permit(:name))
    if @topic.save
      redirect_to @topic
    else
      render :new
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for [@topic, @topic.bookmarks.new] do |f| %>
<div class="col-md-5">
  <div class="form-group">
    <%= f.text_field :link, placeholder: "Enter bookmark url", class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "save", class: 'form-control' %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diggmark</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
   <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
   </ul>
<%= yield %>

  </div>
</body>
</html>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.name, topic %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
  
  <div class="col-md-4">

      <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
  
  </div>
</div>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<%= form_for @topic do |f| %>
   <%= f.label :title %>
<%= f.text_field :name %>
 
  
 
   <%= f.submit "Save" %>
 <% end %>

app/views/topics/show.html.erb
<h2><%= @topic.name %></h2>
  <%= render partial: 'bookmarks/form' %>
  
<% @topic.bookmarks.each do |bookmark| %>
<%= link_to bookmark.link, bookmark.link, target: '_blank' %>
<% end %>

app/views/welcome/about.html.erb
<h1>About Bloccit</h1>
<p>Created by: Me</p>

app/views/welcome/index.html.erb
<h1>Welcome to Bloccit</h1>
<p>This is the home page for Bloccit.</p>